<a href="https://colab.research.google.com/github/FahadMostafa91/FahadMostafa91/blob/main/Python_MachineLearnning_At_A_Glance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basic Examples

In [35]:
from sklearn import neighbors, datasets, preprocessing
from sklearn.model_selection import train_test_split

iris = datasets.load_iris()
X, y = iris.data[:,:2], iris.target
X_train, X_test, y_train, y_test =train_test_split(X,y,random_state=33)
scaler =preprocessing.StandardScaler().fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)
knn = neighbors.KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)


In [ ]:
y_pred

array([1, 1, 0, 2, 1, 2, 0, 0, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0, 2, 2, 0, 0,
       1, 0, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1])

Loading the data

In [12]:
import numpy as np

In [13]:
X = np.random.random((10,5))
y = np.array(['M','M','F','F', 'M','F','M','M','F','F','F'])
X[X <0.7] = 0

Training and Testing data set split 

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X,
                                                   y,
                                                   random_state=0)

Preprocessing the data 

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler ().fit(X_train)
standardized_X = scaler.transform(X_train)
standardized_X_test = scaler.transform(X_test)

Binarization

In [18]:
from sklearn.preprocessing import Binarizer
binarizer = Binarizer (threshold=0.0).fit(X)
binary_X = binarizer.transform(X)

Generating Polynomial Feature 

In [19]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures (5)
poly.fit_transform(X)

array([[1.        , 0.78186016, 0.        , ..., 0.        , 0.        ,
        0.59306663],
       [1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [1.        , 0.        , 0.928198  , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [1.        , 0.96974183, 0.88321032, ..., 0.71122652, 0.69886274,
        0.68671388],
       [1.        , 0.        , 0.94614641, ..., 0.        , 0.        ,
        0.17201567],
       [1.        , 0.8507061 , 0.        , ..., 0.        , 0.        ,
        0.        ]])

Supervised Learning Estimators 

In [20]:
#Linear Regression
from sklearn.linear_model import LinearRegression
lr = LinearRegression(normalize=True)

In [21]:
# Support Vector Machine
from sklearn.svm import SVC
svc = SVC(kernel='linear')

In [22]:
# Naive Bayes Classifier
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB ()

In [23]:
# KNN
from sklearn import neighbors
knn = neighbors.KNeighborsClassifier(n_neighbors=5)

Unsupervised Machine Learning 

In [24]:
# Dimension reduction
# PCA
from sklearn.decomposition import PCA
pca = PCA(n_components=0.95)

In [25]:
# kmeans for clustering 
from sklearn.cluster import KMeans
k_means = KMeans(n_clusters=3, random_state=0)

Model Fitting 

In [26]:
## supervised learning 
# Linear Regression
#lr.fit(X,y)
#Knn
#knn.fit(X_train,y_train)
# SVM
svc.fit(X_train, y_train)
# Unsupervised Learning
k_means.fit(X_train)
pca_model = pca.fit_transform(X_train)

Prediction of the models

In [69]:
# supervised 
y_pred = svc.predict(np.random.random((2,5)))
y_pred = lr.predict (X_test)
y_pred = knn.predict_proba(X_test)
## unsupervised Learning
y_pred = k_means.predict(X_test)

Evaluation of Model Performance 

In [40]:
from sklearn.metrics import accuracy_score
knn.score(X_test,y_test)
accuracy_score(y_test,y_pred)

0.42105263157894735

In [36]:
# evaluation of the model: Classification report
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.42      0.73      0.53        11
           2       0.73      0.42      0.53        19

    accuracy                           0.63        38
   macro avg       0.72      0.72      0.69        38
weighted avg       0.70      0.63      0.63        38



In [42]:
# evaluation of the model: Confusion Matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[3 6 4]
 [4 9 3]
 [1 4 4]]


Regression Matrices 

In [48]:
# mean absolute error # statistical concepts in ML
from sklearn.metrics import mean_absolute_error
y_true = [2 1 0 2 1 2 0 0 1 2 0 0 2 1 2 2 1 0 1 2 0 0 1 0 1 2 1 0 1 1 1 1 0 2 1 1 1 1]
mean_absolute_error(y_true,y_pred)
print(y_pred)

In [46]:
print(y_pred)

[1 1 0 2 1 2 0 0 1 2 2 0 2 1 2 2 1 0 2 2 0 0 1 0 1 2 1 1 1 1 1 1 1 2 1 1 1
 1]


In [49]:
# Mean Absolute Error
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_pred)

0.7105263157894737

In [50]:
# Mean square Error
from sklearn.metrics import mean_absolute_error
mean_square_error(y_test,y_pred)

In [52]:
# R^2 score 
from sklearn.metrics import r2_score
r2_score(y_true,y_pred)

-0.7146341463414636

Clustering Metrices

In [55]:
#Adjusted Rand Index # https://scikit-learn.org/stable/modules/generated/sklearn.metrics.adjusted_rand_score.html?highlight=adjusted%20rand%20index
from sklearn.metrics import adjusted_rand_score
adjusted_rand_score(y_true,y_pred)

-0.02223986582928918

In [56]:
# Homogeneity #https://scikit-learn.org/stable/modules/generated/sklearn.metrics.homogeneity_score.html
from sklearn.metrics import homogeneity_score
homogeneity_score(y_true,y_pred)

0.026719000582312677

In [58]:
# V-measure 
from sklearn.metrics import v_measure_score
metrics.v_measure_score(y_true,y_pred)

Cross Validation

In [68]:
from sklearn_pandas.cross_validation import cross_val_predict
print (cross_val_predict(knn,X_train,y_train, cv=4))
print(cross val score(lr,X,y, cv=2))

Tune Model parameters? Hyperparameter Optimization

In [2]:
#Grid search method
from sklearn.grid_search import GridSearchCV
params = {"n_neighbors": np.arange(1,3),"metric": ["euclidean","cityblock"]}
grid = GridSearchCV(estimator = knn, param_grid =params)
grid.fit(X_train,y_train)
print(grid.best_score_)
print(grid.best_estimator_.n_neighbors)

Randomize Parameter Optimization